wallpaper {
 monitor =
 path = /home/apricity/Pictures/Wallpapers/tokyonight-japan.png
 fit_mode = cover 
}
splash = false
preload = /home/apricity/Pictures/Wallpapers/tokyonight-japan.png
wallpaper = ,/home/apricity/Pictures/Wallpapers/tokyonight-japan.png
