general {
    lock_cmd = pidof hyprlock || hyprlock                                     # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                  # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150
    on-timeout = ddcutil getvcp 10 | grep -oP 'current value =\s*\K\d+' > ~/.config/hypr/hypridle/last_brightness && ddcutil --bus 2 --sleep-multiplier=0.1 setvcp 10 0         
    on-resume = ddcutil --bus 2 --sleep-multiplier=0.1 setvcp 10 $(cat ~/.config/hypr/hypridle/last_brightness)               
}

listener {
    timeout = 300   # 5min
    on-timeout = loginctl lock-session    # lock screen when timeout has passed
}

listener {
    timeout = 360   # 6min
    on-timeout = ddcutil --bus 2 --sleep-multiplier=0.1 --noverify setvcp D6 04  # screen off when timeout has passed
    on-resume = ddcutil --bus 2 --sleep-multiplier=0.1 setvcp D6 01   # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 360                                 # 6min
    on-timeout = systemctl suspend                # suspend pc
}
