wallpaper {
	monitor = eDP-1
	path = ~/.config/hypr/hyprpaper/wallpapers/arch-linux-minimalism-4k-up-1920x1080.jpg
	fit_mode = cover
}

splash = false

preload = ~/.config/hypr/hyprpaper/wallpapers/arch-linux-minimalism-4k-up-1920x1080.jpg
wallpaper = ~/.config/hypr/hyprpaper/wallpapers/arch-linux-minimalism-4k-up-1920x1080.jpg
