general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

# Protect laptop screen from burn in
listener {
    timeout = 120 # 2min
    on-timeout = brightnessctl -s set 5% && brightnessctl -sd rgb:kbd_backlight set 0 # Saves and screen brightness to 5% and turns off keyboard backlight
    on-resume = brightnessctl -r & brightnessctl -rd rgb:kbd_backlight # Resets brightness from save and turns on keyboard backlight
}

listener {
    timeout = 180 # 3min
      on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable", monitor = "eDP-1" })' && brightnessctl -sd rgb:kbd_backlight set 0  # screen & keyboard backlight off when timeout has passed
      on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable", monitor = "eDP-1" })' && brightnessctl -rd rgb:kbd_backlight # screen & keyboard backlight on when activity is detected after timeout has fired.
}

# Locks session after 5 minutes
listener {
    timeout = 300 # 5min
    on-timeout = loginctl lock-session  # lock screen when timeout has passed
}


