#############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps 
windowrule {
  name = windowrule-1
  suppress_event = maximize
  match:class = .*
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-2
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}

windowrule {
  name = email-workspace 
  match:title = .*(?i)($mailClient).*
  workspace = special:mail
  float = on # Needed to make size work
  size = (monitor_w*.8) (monitor_h*.8) 
  center = on # Makes sure window is centered
  opacity = 0.92 0.92 1
}

windowrule {
  name = system-monitor-workspace
  match:initial_class = ^(system-monitor)$
  workspace = special:sysmon
  float = on
  size = (monitor_w*.8) (monitor_h*.8)
  center = on
  opacity = 0.9 0.9 1 
}

# Make these workspaces persistent so they show up in waybar
workspace = 1, monitor:eDP-1, persistent:true
workspace = 2, monitor:eDP-1, persistent:true
workspace = 3, monitor:eDP-1, persistent:true
workspace = 4, monitor:eDP-1, persistent:true
workspace = 5, monitor:eDP-1, persistent:true

# See https://wiki.hypr.land/Configuring/Environment-variables/

# unscale XWayland
    xwayland {
    force_zero_scaling = true
  }

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24


