# Hyprland idle management daemon
exec-once = hypridle 
# Notification daemon
exec-once = dunst
# Automatically mounts storage devices
exec-once = udiskie
# Start the bar 
exec-once = waybar 
# Start the background clock
exec-once = waybar -c ~/.config/waybar-clock/config.jsonc -s ~/.config/waybar-clock/style.css
# Hyprpaper
exec-once = hyprpaper
# Hyprsunset
exec-once = hyprsunset
# Cliphist
exec-once = wl-paste --type text --watch cliphist store 
exec-once = wl-paste --type image --watch cliphist store
