$font = 'HackNFM-Regular'

general {
    hide_cursor = false
    screencopy_mode = 0
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor = 
    path = ~/.config/hypr/hyprpaper/wallpapers/arch-linux-minimalism-4k-up-1920x1080.jpg
    blur_passes = 2
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba({{color14 | strip}}ee) rgba({{color3 | strip}}ee) 90deg
    check_color = rgba({{cursor | strip}}ee) rgba({{cursor | darken(0.4) | strip}}ee) 120deg
    fail_color = rgba({{color14 | blend(cursor) | strip}}ee) rgba({{color14 | blend(cursor) | strip}}ee) 40deg

    font_color = rgb(143, 143, 143)
    fade_on_empty = false
    rounding = 15

    font_family = $font
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -80
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12 # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 90
    font_family = $font

    position = 0, -250
    halign = center 
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    font_family = $font

    position = 0, -400
    halign = center 
    valign = top
}    

# RANDOM PHRASE
label {
    monitor = 
    text = cmd[once] ~/.config/hypr/hyprlock/randompass.sh
    font_size = 50
    font_family = $font

    position = 0, 50
    halign = center
    valign = center
}
